[workspace]
authors = []
channels = ["conda-forge"]
name = "workshop-open-source-geospatial"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
render = "myst build --strict --html"
preview = "myst start"

[dependencies]
mystmd = ">=1.7.0,<2"
