channels:
  - "conda-forge"
  - "nodefaults"
dependencies:
  - "python==3.13"
  - "jupyterlab>=4.4.2"

  # Some cool extensions
  - "jupyterlab-favorites <3.3.0"  # 3.3.0 seems to introduce a bug duplicating headers in Notebook Markdown cells (https://github.com/jupyterlab-contrib/jupyterlab-favorites/issues/35)
  - "jupyter-collaboration>=3,<4"
  - "jupyter-server-proxy"
  - "jupyterlab-myst"
  - "jupyterlab-geojson"
  - "jupyterlab_execute_time"
  - "nbdime"

  # Python mainstays
  - "numpy"
  - "matplotlib"
  - "hvplot"
  - "pandas"
  - "scipy"
  - "xarray"

  # geo
  - "gdal"
  - "geopandas"
  - "rasterio"
  - "rioxarray"
  - "shapely"
  - "fiona"
  - "pystac-client"
  - "odc-stac"
  - "ibis-duckdb"
  - "exactextract"

  # geo viz
  - "jupytergis >=0.10.1"
  - "leafmap"
  - "folium"
  - "cartopy"
  - "geoviews"
  - "maplibre"

  # Publishing
  - "mystmd >=1.7.0"
  - "typst"
  - "jupyter-myst-build-proxy >=0.6.0"

  # Testing and validation
  - "ruff"
  - "pre-commit"

  # GitHub utilities
  - "gh"
  - "gh-scoped-creds"

  # Infrastructure
  - "jupyter-server-proxy"  # Enable proxying MyST sites built from CLI, accessed at `$PREFIX/proxy/$PORT`
